=== Bhaskers-Blu-Org2/ability-attributes/generator/schema-schema.json
{
  "$id": "ability-attributes-schema",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "definitions": {
    "AttributeEntry": {
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[A-Za-z_][A-Za-z0-9_-]*$"
        },
        "value": {
          "anyOf": [
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "string"
            }
          ]
        },
        "optional": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "value"
      ],
      "type": "object"
    },
    "AttributeInAssumption": {
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[A-Za-z_][A-Za-z0-9_-]*$"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "value"
      ],
      "type": "object"
    },
    "AttributeInParameter": {
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[A-Za-z_][A-Za-z0-9_-]*$"
        },
        "constraints": {
          "items": {
            "anyOf": [
              {
                "$ref": "ability-attributes-schema#/definitions/ConstraintEntries"
              },
              {
                "$ref": "ability-attributes-schema#/definitions/ConstraintRef"
              }
            ]
          },
          "type": "array"
        },
        "value": {
          "items": {
            "$ref": "ability-attributes-schema#/definitions/ParameterValue"
          },
          "type": "array"
        },
        "optional": {
          "type": "boolean"
        }
      },
      "required": [
        "name"
      ],
      "type": "object"
    },
    "AttributeRef": {
      "additionalProperties": false,
      "properties": {
        "ref": {
          "type": "string"
        }
      },
      "required": [
        "ref"
      ],
      "type": "object"
    },
    "Attributes": {
      "patternProperties": {
        "^\\$[A-Za-z_][A-Za-z0-9_-]+$": {
          "anyOf": [
            {
              "$ref": "ability-attributes-schema#/definitions/AttributeEntry"
            },
            {
              "additionalProperties": false,
              "properties": {
                "one": {
                  "items": {
                    "$ref": "ability-attributes-schema#/definitions/AttributeEntry"
                  },
                  "type": "array"
                }
              },
              "required": [
                "one"
              ],
              "type": "object"
            }
          ]
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Class": {
      "additionalProperties": false,
      "properties": {
        "assumptions": {
          "items": {
            "anyOf": [
              {
                "additionalProperties": false,
                "properties": {
                  "attributes": {
                    "items": {
                      "$ref": "#/definitions/AttributeInAssumption"
                    },
                    "type": "array"
                  },
                  "tag": {
                    "type": "string",
                    "pattern": "^\\s*\\<\\s*[a-z][a-z0-9_-]*\\s*\\>\\s*$"

                  }
                },
                "required": [
                  "attributes",
                  "tag"
                ],
                "type": "object"
              },
              {
                "additionalProperties": false,
                "properties": {
                  "tag": {
                    "type": "string",
                    "pattern": "^\\s*\\<\\s*[a-z][a-z0-9_-]*\\s*\\>\\s*$"
                  }
                },
                "required": [
                  "tag"
                ],
                "type": "object"
              },
              {
                "additionalProperties": false,
                "properties": {
                  "attributes": {
                    "items": {
                      "$ref": "#/definitions/AttributeInAssumption"
                    },
                    "type": "array"
                  }
                },
                "required": [
                  "attributes"
                ],
                "type": "object"
              }
            ]
          },
          "type": "array"
        },
        "constraints": {
          "items": {
            "anyOf": [
              {
                "$ref": "ability-attributes-schema#/definitions/ConstraintEntries"
              },
              {
                "$ref": "ability-attributes-schema#/definitions/ConstraintRef"
              }
            ]
          },
          "type": "array"
        },
        "parameters": {
          "items": {
            "anyOf": [
              {
                "$ref": "ability-attributes-schema#/definitions/ParameterInClassEntry"
              },
              {
                "$ref": "ability-attributes-schema#/definitions/ParameterRefRel"
              },
              {
                "additionalProperties": false,
                "properties": {
                  "one": {
                    "items": {
                      "$ref": "ability-attributes-schema#/definitions/ParameterEntry"
                    },
                    "type": "array"
                  },
                  "optional": {
                    "$ref": "ability-attributes-schema#/definitions/ParameterOptional"
                  }
                },
                "required": [
                  "one"
                ],
                "type": "object"
              }
            ]
          },
          "type": "array"
        },
        "tags": {
          "type": "object",
          "patternProperties": {
            "^\\s*\\<\\s*[a-z][a-z0-9_-]*\\s*\\>\\s*(,\\s*\\<\\s*[a-z][a-z0-9_-]*\\s*\\>\\s*)*$": {
              "$ref": "ability-attributes-schema#/definitions/Tag"
            }
          },
          "additionalProperties": false
        }
      },
      "required": [
        "tags"
      ],
      "type": "object"
    },
    "Classes": {
      "type": "object",
      "patternProperties": {
        "^[A-Za-z_][A-Za-z0-9_]*$": {
          "$ref": "ability-attributes-schema#/definitions/Class"
        }
      },
      "additionalProperties": false
    },
    "ConstraintEntry": {
      "anyOf": [
        {
          "additionalProperties": false,
          "properties": {
            "description": {
              "type": "string"
            },
            "xpath": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "xpath"
          ],
          "type": "object"
        },
        {
          "additionalProperties": false,
          "properties": {
            "description": {
              "type": "string"
            },
            "js": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "js"
          ],
          "type": "object"
        }
      ]
    },
    "ConstraintEntries": {
      "anyOf": [
        {
          "$ref": "ability-attributes-schema#/definitions/ConstraintEntry"
        },
        {
          "additionalProperties": false,
          "properties": {
            "one": {
              "items": {
                "$ref": "ability-attributes-schema#/definitions/ConstraintEntry"
              },
              "type": "array"
            }
          },
          "required": [
            "one"
          ],
          "type": "object"
        }
      ]
    },
    "ConstraintRef": {
      "additionalProperties": false,
      "properties": {
        "ref": {
          "type": "string"
        }
      },
      "required": [
        "ref"
      ],
      "type": "object"
    },
    "Constraints": {
      "additionalProperties": false,
      "patternProperties": {
        "^\\$[A-Za-z_][A-Za-z0-9_-]+$": {
          "$ref": "ability-attributes-schema#/definitions/ConstraintEntries"
        }
      },
      "type": "object"
    },
    "ParameterEntry": {
      "additionalProperties": false,
      "properties": {
        "attributes": {
          "items": {
            "$ref": "#/definitions/AttributeInParameter"
          },
          "type": "array"
        },
        "name": {
          "type": "string",
          "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
        }
      },
      "required": [
        "attributes",
        "name"
      ],
      "type": "object"
    },
    "ParameterInClassEntry": {
      "additionalProperties": false,
      "properties": {
        "attributes": {
          "items": {
            "$ref": "#/definitions/AttributeInParameter"
          },
          "type": "array"
        },
        "name": {
          "type": "string",
          "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
        },
        "optional": {
          "$ref": "ability-attributes-schema#/definitions/ParameterOptional"
        }
      },
      "required": [
        "attributes",
        "name"
      ],
      "type": "object"
    },
    "ParameterOptional": {
      "anyOf": [
        {
          "$ref": "ability-attributes-schema#/definitions/ConstraintEntries"
        },
        {
          "$ref": "ability-attributes-schema#/definitions/ConstraintRef"
        },
        {
          "type": "boolean"
        }
      ]
    },
    "ParameterRef": {
      "additionalProperties": false,
      "properties": {
        "optional": {
          "$ref": "ability-attributes-schema#/definitions/ParameterOptional"
        },
        "ref": {
          "type": "string"
        }
      },
      "required": [
        "ref"
      ],
      "type": "object"
    },
    "ParameterRel": {
      "additionalProperties": false,
      "properties": {
        "rel": {
          "type": "string",
          "pattern": "^@[A-Za-z_][A-Za-z0-9_-]+$"
        }
      },
      "required": [
        "rel"
      ],
      "type": "object"
    },
    "ParameterRefRel": {
      "anyOf": [
        {
          "$ref": "ability-attributes-schema#/definitions/ParameterRef"
        },
        {
          "$ref": "ability-attributes-schema#/definitions/ParameterRel"
        }
      ]
    },
    "ParameterValue": {
      "additionalProperties": false,
      "properties": {
        "attribute": {
          "type": [
            "string",
            "boolean"
          ]
        },
        "parameter": {
          "type": [
            "null",
            "string",
            "number",
            "boolean"
          ]
        }
      },
      "required": [
        "attribute",
        "parameter"
      ],
      "type": "object"
    },
    "Parameters": {
      "patternProperties": {
        "^\\$[A-Za-z_][A-Za-z0-9_-]+$": {
          "anyOf": [
            {
              "$ref": "ability-attributes-schema#/definitions/ParameterEntry"
            },
            {
              "additionalProperties": false,
              "properties": {
                "one": {
                  "items": {
                    "$ref": "ability-attributes-schema#/definitions/ParameterEntry"
                  },
                  "type": "array"
                }
              },
              "required": [
                "one"
              ],
              "type": "object"
            }
          ]
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Tag": {
      "additionalProperties": false,
      "properties": {
        "attributes": {
          "items": {
            "anyOf": [
              {
                "$ref": "ability-attributes-schema#/definitions/AttributeEntry"
              },
              {
                "additionalProperties": false,
                "properties": {
                  "one": {
                    "items": {
                      "$ref": "ability-attributes-schema#/definitions/AttributeEntry"
                    },
                    "type": "array"
                  }
                },
                "required": [
                  "one"
                ],
                "type": "object"
              },
              {
                "$ref": "ability-attributes-schema#/definitions/AttributeRef"
              }
            ]
          },
          "type": "array"
        },
        "constraints": {
          "items": {
            "anyOf": [
              {
                "$ref": "ability-attributes-schema#/definitions/ConstraintEntries"
              },
              {
                "$ref": "ability-attributes-schema#/definitions/ConstraintRef"
              }
            ]
          },
          "type": "array"
        },
        "parameters": {
          "additionalProperties": false,
          "patternProperties": {
            "^@[A-Za-z_][A-Za-z0-9_-]+$": {
              "anyOf": [
                {
                  "$ref": "ability-attributes-schema#/definitions/ParameterInClassEntry"
                },
                {
                  "$ref": "ability-attributes-schema#/definitions/ParameterRef"
                },
                {
                  "additionalProperties": false,
                  "properties": {
                    "one": {
                      "items": {
                        "$ref": "ability-attributes-schema#/definitions/ParameterEntry"
                      },
                      "type": "array"
                    },
                    "optional": {
                      "$ref": "ability-attributes-schema#/definitions/ParameterOptional"
                    }
                  },
                  "required": [
                    "one"
                  ],
                  "type": "object"
                }
              ]
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    }
  },
  "properties": {
    "attributes": {
      "$ref": "ability-attributes-schema#/definitions/Attributes"
    },
    "classes": {
      "$ref": "ability-attributes-schema#/definitions/Classes"
    },
    "constraints": {
      "$ref": "ability-attributes-schema#/definitions/Constraints"
    },
    "namespace": {
      "type": "string",
      "pattern": "^[A-Za-z_][A-Za-z0-9_-]*$"
    },
    "parameters": {
      "$ref": "ability-attributes-schema#/definitions/Parameters"
    },
    "version": {
      "type": "string",
      "pattern": "^1\\.0$"
    }
  },
  "required": [
    "classes",
    "version"
  ],
  "type": "object"
}

=== Bhaskers-Blu-Org2/ability-attributes/demo/schema.json
{
    "version": "1.0",

    "constraints": {
        "$atomic": {
            "xpath": "not(boolean(.//*[@role and @role != 'none' and @role != 'presentation'] | .//a | .//area | .//button | .//input | .//object | .//select | .//textarea))",
            "description": "Component cannot contain other accessible components"
        },

        "$hasText": {
            "xpath": ".//text()[normalize-space(.) != '']",
            "description": "Component must contain text nodes"
        },

        "$existingIDs": {
            "js": "checkIdentifiers",
            "description": "Value must be space-separated list of existing element identifiers"
        }
    },

    "parameters": {
        "$label": {
            "one": [
                {
                    "name": "label",
                    "attributes": [
                        {
                            "name": "aria-label"
                        }
                    ]
                },
                {
                    "name": "labelledBy",
                    "attributes": [
                        {
                            "name": "aria-labelledby",
                            "constraints": [{ "ref": "$existingIDs" }]
                        }
                    ]
                }
            ]
        },

        "$describedBy": {
            "name": "describedBy",
            "attributes": [
                {
                    "name": "aria-describedby",
                    "constraints": [{ "ref": "$existingIDs" }]
                }
            ]
        },

        "$checked": {
            "name": "checked",
            "attributes": [
                {
                    "name": "aria-checked",
                    "value": [
                        { "parameter": true, "attribute": "true" },
                        { "parameter": false, "attribute": false }
                    ]
                }
            ]
        },

        "$disabled": {
            "name": "disabled",
            "attributes": [
                {
                    "name": "disabled",
                    "value": [
                        { "parameter": true, "attribute": true },
                        { "parameter": false, "attribute": false }
                    ]
                },
                {
                    "name": "aria-disabled",
                    "value": [
                        { "parameter": true, "attribute": "true" },
                        { "parameter": false, "attribute": "false" }
                    ],
                    "optional": true
                }
            ]
        },

        "$disabled-custom": {
            "name": "disabled",
            "attributes": [
                {
                    "name": "aria-disabled",
                    "value": [
                        { "parameter": true, "attribute": "true" },
                        { "parameter": false, "attribute": false }
                    ]
                },
                {
                    "name": "disabled",
                    "value": [
                        { "parameter": true, "attribute": true },
                        { "parameter": false, "attribute": false }
                    ],
                    "optional": true
                }
            ]
        },

        "$tabbable": {
            "name": "tabbable",
            "attributes": [
                {
                    "name": "tabindex",
                    "value": [
                        { "parameter": true, "attribute": "0" },
                        { "parameter": false, "attribute": "-1" }
                    ]
                }
            ]
        }
    },

    "attributes": {
        "$tabindex": {
            "name": "tabindex",
            "value": ["0", "-1"]
        }
    },

    "classes": {
        "Body": {
            "assumptions": [{ "tag": "<body>" }],
            "tags": { "<body>": {} }
        },

        "Header1": {
            "assumptions": [
                { "tag": "<h1>" },
                { "tag": "<div>", "attributes": [{ "name": "role", "value": "heading" }, { "name": "aria-level", "value": "1" }] }
            ],

            "parameters": [
                { "ref": "$label", "optional": { "ref": "$hasText" } }
            ],

            "tags": {
                "<h1>": {},
                "<div>": {
                    "attributes": [
                        { "name": "role", "value": "heading" },
                        { "name": "aria-level", "value": "1" }
                    ]
                }
            }
        },

        "Button": {
            "assumptions": [
                { "tag": "<button>" },
                { "tag": "<div>", "attributes": [{ "name": "role", "value": "button" }] }
            ],

            "constraints": [
                { "ref": "$atomic" }
            ],

            "parameters": [
                { "rel": "@label" },
                { "ref": "$describedBy", "optional": true },
                { "rel": "@tabbable" },
                { "rel": "@disabled" }
            ],

            "tags": {
                "<button>": {
                    "parameters": {
                        "@label": { "ref": "$label", "optional": { "ref": "$hasText" } },
                        "@tabbable": { "ref": "$tabbable", "optional": true },
                        "@disabled": { "ref": "$disabled", "optional": true }
                    },
                    "attributes": [
                        { "name": "role", "value": "button", "optional": true }
                    ]
                },

                "<input>": {
                    "parameters": {
                        "@label": {
                            "ref": "$label",
                            "optional": {
                                "xpath": "normalize-space(@value) != ''",
                                "description": "Component must contain value attribute"
                            }
                        },
                        "@tabbable": { "ref": "$tabbable", "optional": true },
                        "@disabled": { "ref": "$disabled", "optional": true }
                    },
                    "attributes": [
                        { "name": "type", "value": ["button", "submit", "reset"] },
                        { "name": "role", "value": "button", "optional": true }
                    ]
                },

                "<div>, <span>": {
                    "parameters": {
                        "@label": { "ref": "$label", "optional": { "ref": "$hasText" } },
                        "@tabbable": { "ref": "$tabbable", "optional": true },
                        "@disabled": { "ref": "$disabled-custom", "optional": true }
                    },
                    "attributes": [
                        { "name": "role", "value": "button" },
                        { "ref": "$tabindex" }
                    ]
                }
            }
        },

        "Checkbox": {
            "constraints": [
                { "ref": "$atomic" }
            ],

            "parameters": [
                { "ref": "$label", "optional": { "ref": "$hasText" } },
                { "ref": "$checked" },
                { "ref": "$describedBy", "optional": true },
                { "ref": "$tabbable", "optional": true }
            ],

            "tags": {
                "<input>": {
                    "attributes": [
                        { "name": "type", "value": "checkbox" }
                    ]
                },

                "<div>, <span>": {
                    "attributes": [
                        { "name": "role", "value": "checkbox" },
                        { "ref": "$tabindex" }
                    ]
                }
            }
        }
    }
}
